### ISSUE TITLE
UUoC in solutions

### ISSUE THREAD

**Issue by dkalaluhi** [kennyyu/bootcamp-unix#1]
Just a thought, but going through the bootcamp, I noticed there's a lot of use of cat, when it's not needed. Why `cat data.txt` only to pipe that output to `awk` when we can do that directly:

eg. Problem 9 of Scavenger Hunt: part 1.

> For the next few questions, you may find this useful: If you feed in a file with one number on each line to this command: python -c "import sys; print sum(int(line) for line in sys.stdin)", this will sum all the numbers. Sum all the numbers in the second column of data.txt. 

And solution:

> `cat data.txt | awk '{print $2}' | python -c "import sys; print sum(int(line) for line in sys.stdin)"`

It would much more efficient to just do the following:

`awk '{print $2}' data.txt | python -c "import sys; print sum(int(line) for line in sys.stdin)"`

The same can be said for things like `grep` and `wc` as well

**Comment by kennyyu** [comment]
Yep, you are right! I'm creating an extra process unnecessarily with the additional `cat` commands. The reason for this was that when I was originally building the exercises, I built the problems and solutions in steps, e.g., 
1. First check what's in the file as a sanity check (`cat ...`)
2. Now let's get a column (add `| awk ...`, no need to adjust `cat` command before this)
3. Get the sum (add `| python ...`, no need to adjust commands before this)

and so forth. So the `cat` commands are artifacts of when I was originally writing the problems.
